import { TacticalModule } from './types';

export const TACTICAL_MODULES_CATALOG: TacticalModule[] = [
  // 1. Mensajería P2P & Canales (6)
  {
    id: "channels",
    name: "Canales Mesh Locales",
    category: "Mensajería & Canales",
    icon: "📻",
    summary: "Subcanales temáticos de escuadrón (#general, #sos, #logistica) sobre broadcast Gossipsub.",
    badge: "Multi-Topic",
    techStack: "Rust Mesh Kernel / Sled DB",
    details: "Permite la creación de salas de mensajería efímeras o persistentes por temas dentro del rango de radio de la malla local. Los mensajes son propagados por todos los nodos cercanos y deduplicados por 72 horas.",
    latency: "< 45ms",
    encryption: "Noise XK + ChaCha20-Poly1305"
  },
  {
    id: "socialFeed",
    name: "RED Social Feed P2P",
    category: "Mensajería & Canales",
    icon: "🌍",
    summary: "Muro de publicaciones públicas descentralizadas propagadas mediante mulas de datos DTN.",
    badge: "DTN Feed",
    techStack: "Ed25519 Signed Payloads",
    details: "Red social resistente a censura donde cada publicación está firmada por la clave privada Ed25519 del autor y viaja de dispositivo en dispositivo mediante saltos oportunistas (Sneakernet) sin servidores.",
    latency: "Asíncrono DTN",
    encryption: "Ed25519 / Merkle Tree"
  },
  {
    id: "broadcast",
    name: "Difusión Privada",
    category: "Mensajería & Canales",
    icon: "📢",
    summary: "Emisión unidireccional de alertas cifradas a listas cerradas de contactos autorizados.",
    badge: "Cifrado E2E",
    techStack: "ChaCha20-Poly1305",
    details: "Emite comunicados urgentes o boletines a múltiples destinatarios pre-aprobados de forma simultánea, cifrando cada paquete individualmente para garantizar la privacidad de los miembros de la lista.",
    latency: "< 60ms",
    encryption: "Double Ratchet E2E"
  },
  {
    id: "walkie",
    name: "Walkie-Talkie Mesh HQ (PTT)",
    category: "Mensajería & Canales",
    icon: "🎙️",
    summary: "Push-To-Talk con auto-reproducción instantánea en canales de voz usando LowBitrateVocoder.",
    badge: "Ultra-Low Latency",
    techStack: "8kHz IMA-ADPCM / PTT DSP",
    details: "Canal de radio por voz full-duplex optimizado para rescate o coordinación táctica. Al presionar el botón PTT, la voz se comprime a 1.6-3.2 kbps y se auto-reproduce instantáneamente en los terminales del escuadrón.",
    latency: "< 90ms",
    encryption: "ChaCha20-Poly1305 Audio"
  },
  {
    id: "canvas",
    name: "Canvas Táctico P2P",
    category: "Mensajería & Canales",
    icon: "🎨",
    summary: "Pizarra interactiva colaborativa en tiempo real con sincronización de trazos vectoriales.",
    badge: "Zero-Server",
    techStack: "CRDT / WebRTC DataChannel",
    details: "Mesa de operaciones visual donde los rescatistas o brigadas dibujan mapas, rutas de evacuación y zonas seguras con sincronización vectorial en tiempo real sin conexión a internet.",
    latency: "< 30ms",
    encryption: "WebRTC DTLS / SRTP"
  },
  {
    id: "liveStream",
    name: "Live Broadcast Stream",
    category: "Mensajería & Canales",
    icon: "📺",
    summary: "Transmisión de vídeo en vivo P2P de baja latencia con señalización descentralizada.",
    badge: "WebRTC Mesh",
    techStack: "H.264 / WebRTC Mesh",
    details: "Streaming de vídeo táctico punto a punto o retransmitido por nodos repetidores. Diseñado para reconocimiento aéreo con drones o monitoreo de perímetros en zonas sin cobertura celular.",
    latency: "< 250ms",
    encryption: "DTLS 1.3 / ChaCha20"
  },

  // 2. Red Malla & Radar Off-Grid (9)
  {
    id: "shakePair",
    name: "Shake & Pair (Acelerómetro)",
    category: "Red Malla & Radar",
    icon: "📳",
    summary: "Emparejamiento criptográfico instantáneo agitando ambos dispositivos mediante sensores físicos.",
    badge: "Hardware Sensor",
    techStack: "Android Sensor API / BLE Scan",
    details: "Agitar dos teléfonos al mismo tiempo genera un vector de entropía cinemática correlacionada por acelerómetro que autentica e intercambia claves públicas de forma física y previene ataques Man-in-the-Middle.",
    latency: "< 500ms",
    encryption: "Sensor Entropy / Ed25519"
  },
  {
    id: "offGridCompass",
    name: "Radar Topográfico GPS",
    category: "Red Malla & Radar",
    icon: "🧭",
    summary: "Brújula militar off-grid que proyecta rumbo angular y distancia a nodos pares.",
    badge: "Geolocalización",
    techStack: "Haversine / Magnetometer API",
    details: "Calcula de forma puramente matemática la trayectoria azimutal y distancia euclidiana hacia los demás miembros de la patrulla utilizando coordenadas GPS embebidas en los handshakes de radio.",
    latency: "< 20ms",
    encryption: "Cifrado Geocercado"
  },
  {
    id: "nodemap",
    name: "Mapa de Nodos P2P",
    category: "Red Malla & Radar",
    icon: "🗺️",
    summary: "Cartografía táctica de nodos con renderizado vectorial de rutas multi-salto activas.",
    badge: "Topología Geo",
    techStack: "Leaflet / GPS Coordinates",
    details: "Muestra visualmente la posición relativa de cada nodo en el mapa satelital precargado y dibuja las líneas de enlace de radio activas, señalando la calidad del enlace RSSI de cada salto.",
    latency: "< 40ms",
    encryption: "Bóveda Local Cifrada"
  },
  {
    id: "nearby",
    name: "Radar Hardware BLE/WiFi",
    category: "Red Malla & Radar",
    icon: "📡",
    summary: "Escaneo en tiempo real de potencia RSSI, estado de batería y paquetes recibidos.",
    badge: "Radio Raw",
    techStack: "BLE GATT HCI / WiFi Sniffer",
    details: "Monitorea continuamente el espectro electromagnético cercano para detectar balizas de presencia de otros terminales RED, midiendo la intensidad de señal de -30 dBm (contacto cercano) a -95 dBm (límite).",
    latency: "< 100ms",
    encryption: "HMAC Blind Beacon"
  },
  {
    id: "rfSpectrum",
    name: "Analizador Espectro RF / EW",
    category: "Red Malla & Radar",
    icon: "🛡️",
    summary: "Detección de interferencias electrónicas (EW jamming) y análisis de canales 2.4GHz / 915MHz.",
    badge: "Anti-Jamming",
    techStack: "RSSI Variance / Spectral DSP",
    details: "Analiza la varianza y piso de ruido del receptor de radio. Si detecta un ataque de denegación de espectro (Jammer), conmuta automáticamente los paquetes al canal ultrasónico SoundMesh o LoRa.",
    latency: "< 15ms",
    encryption: "Frequency Hopping"
  },
  {
    id: "proximity",
    name: "Ondas de Proximidad",
    category: "Red Malla & Radar",
    icon: "🌊",
    summary: "Radar sonar acústico y de radio que detecta la densidad de dispositivos soberanos.",
    badge: "Proximity Ping",
    techStack: "BLE Beaconing / SoundMesh",
    details: "Genera un pulso periódico sonar que calcula la densidad de nodos amigos en un radio de 50 metros para advertir de agrupaciones de personal o pérdida de contacto de retaguardia.",
    latency: "< 80ms",
    encryption: "Rolling Ephemeral Hash"
  },
  {
    id: "weather",
    name: "Clima & Barómetro CAP",
    category: "Red Malla & Radar",
    icon: "🌤️",
    summary: "Alertas meteorológicas de emergencia CAP y barómetro local para predicción de tormentas.",
    badge: "Sensor Barométrico",
    techStack: "CAP XML / Pressure Sensor",
    details: "Monitorea el sensor barométrico del hardware para predecir caídas bruscas de presión atmosférica asociadas a huracanes o tormentas severas y difunde alertas de protocolo CAP a la comunidad.",
    latency: "< 10ms",
    encryption: "Firma Digital CAP"
  },
  {
    id: "ecoMesh",
    name: "Batería Eco-Mesh",
    category: "Red Malla & Radar",
    icon: "🔋",
    summary: "Gobernador cinemático de energía (KineticDutyGovernor) que modula la radio.",
    badge: "Ahorro Dinámico",
    techStack: "Battery API / Gyroscope",
    details: "Ajusta la tasa de muestreo y escaneo de radio según el giroscopio y el nivel de batería restante, extendiendo la autonomía del terminal de 24 horas hasta 7 días en operaciones de supervivencia.",
    latency: "Tiempo Real",
    encryption: "N/A"
  },
  {
    id: "network",
    name: "Topología de Red",
    category: "Red Malla & Radar",
    icon: "🌐",
    summary: "Grafo interactivo de enrutamiento Kademlia DHT, tabla de pares y métricas de latencia.",
    badge: "DHT Routing",
    techStack: "LibP2P Kademlia / Axum SSE",
    details: "Permite inspeccionar visualmente la tabla de enrutamiento XOR de Kademlia, los árboles de suscripción Gossipsub y los túneles DCUtR de evasión de NATs simétricos celulares.",
    latency: "< 25ms",
    encryption: "LibP2P SecIO / Noise"
  },

  // 3. Identidad, Pagos & Soberanía (9)
  {
    id: "commercialHub",
    name: "Hub Comercial & Recompensas",
    category: "Identidad & Pagos",
    icon: "⚡",
    summary: "Economía DePIN de retransmisión: gana tokens $RED por reenviar paquetes ajenos.",
    badge: "Proof-of-Relay",
    techStack: "Tokenomics / Relay Ledger",
    details: "Premia a los nodos que sirven como repetidores en zonas remotas. Cada paquete retransmitido exitosamente genera un comprobante de servicio criptográfico canjeable por recompensas en la red.",
    latency: "< 200ms",
    encryption: "Merkle Proof-of-Relay"
  },
  {
    id: "web3Vault",
    name: "Bóveda Web3 & MetaMask",
    category: "Identidad & Pagos",
    icon: "🦊",
    summary: "Firma EIP-712 sin gas y enlace multi-cadena con billeteras EVM en Polygon / Ethereum.",
    badge: "EVM Bridge",
    techStack: "Ethers.js / EIP-712",
    details: "Permite vincular tu dirección pública de Ethereum/Polygon a tu identidad soberana did:red para firmar mensajes autenticados y participar en contratos inteligentes descentralizados.",
    latency: "< 150ms",
    encryption: "Secp256k1 / EIP-712"
  },
  {
    id: "idVault",
    name: "Perfil & Bóveda DID",
    category: "Identidad & Pagos",
    icon: "🪪",
    summary: "Identidad auto-soberana W3C did:red basada en clave pública Ed25519 con QR.",
    badge: "Self-Sovereign",
    techStack: "W3C DID / Ed25519",
    details: "Tu identidad digital no pertenece a ninguna empresa ni gobierno. Es un par de claves criptográficas derivadas matemáticamente en tu teléfono, exportable como código QR táctico.",
    latency: "< 5ms",
    encryption: "Ed25519 / Curve25519"
  },
  {
    id: "p2pPay",
    name: "Pagos & Vouchers P2P",
    category: "Identidad & Pagos",
    icon: "💳",
    summary: "Emisión y canje de vales de pago offline firmados criptográficamente con paridad fiat.",
    badge: "Offline Cash",
    techStack: "Ed25519 Blind Signatures",
    details: "Permite realizar transacciones comerciales durante apagones financieros o cortes de tarjetas. Los vales se transmiten por Bluetooth y se validan mediante firmas ciegas Ed25519 sin banco.",
    latency: "< 80ms",
    encryption: "ChaCha20 / Ed25519"
  },
  {
    id: "pqcCrypto",
    name: "Bóveda Criptográfica PQC",
    category: "Identidad & Pagos",
    icon: "🔐",
    summary: "Criptografía híbrida post-cuántica ML-KEM-768 (FIPS 203) combinada con Double Ratchet.",
    badge: "Post-Quantum",
    techStack: "ML-KEM-768 / Noise XK",
    details: "Combina el estándar de encapsulamiento en retículos ML-KEM-768 con el protocolo Signal Double Ratchet para blindar todas las conversaciones contra futuras computadoras cuánticas.",
    latency: "< 12ms",
    encryption: "ML-KEM-768 ⊕ X25519"
  },
  {
    id: "explorer",
    name: "Explorador Blockchain",
    category: "Identidad & Pagos",
    icon: "⛓️",
    summary: "Auditoría de bloques y transacciones de la cadena de bloques liviana interna.",
    badge: "Micro-Chain",
    techStack: "Merkle Trees / PoS Consensus",
    details: "Visualizador de la micro-cadena distribuida del ecosistema RED que registra las operaciones críticas de estado, revocaciones de identidad y recompensas de retransmisión sin consumir gigabytes.",
    latency: "< 50ms",
    encryption: "BLAKE3 Merkle DAG / ChaCha20-Poly1305"
  },
  {
    id: "webCompanionLink",
    name: "Vincular Dispositivo Web (PC)",
    category: "Identidad & Pagos",
    icon: "💻",
    summary: "Puente cifrado P2P que sincroniza la bóveda entre el celular y el navegador de la PC.",
    badge: "Sync Local",
    techStack: "WebRTC DataChannel / AES-256",
    details: "Escanea el código QR de la pantalla de tu computadora desde tu celular Android para establecer un túnel WebRTC cifrado directo en red local sin que los mensajes toquen servidores externos.",
    latency: "< 35ms",
    encryption: "AES-256-GCM / WebRTC"
  },
  {
    id: "stegoVault",
    name: "Bóveda Esteganográfica",
    category: "Identidad & Pagos",
    icon: "🖼️",
    summary: "Ocultamiento de claves privadas y mensajes dentro de píxeles de fotografías.",
    badge: "Anti-Forensics",
    techStack: "LSB Steganography / ChaCha20",
    details: "Incrusta datos altamente confidenciales modificando de forma imperceptible los bits menos significativos (LSB) de imágenes JPEG/PNG, haciéndolos invisibles ante escáneres forenses.",
    latency: "< 120ms",
    encryption: "ChaCha20 + LSB Matrix"
  },
  {
    id: "backup",
    name: "Respaldos & Restauración",
    category: "Identidad & Pagos",
    icon: "💾",
    summary: "Copia de seguridad 1-toque protegida por PIN Maestro con semilla BIP-39.",
    badge: "Zero-Knowledge",
    techStack: "Argon2id / AES-GCM-256",
    details: "Exporta tu bóveda en un contenedor hermético cifrado con Argon2id. Puedes recuperarla en cualquier dispositivo mediante una frase mnemónica de 12 palabras o archivo cifrado.",
    latency: "< 300ms",
    encryption: "Argon2id / AES-256-GCM"
  },

  // 4. Ciberdefensa & Escudo Global (4)
  {
    id: "globalShield",
    name: "Escudo Global (DEFCON Matrix)",
    category: "Ciberdefensa",
    icon: "🛡️",
    summary: "Matriz táctica de niveles de amenaza (DEFCON 5 a 1) que endurece las políticas de radio.",
    badge: "DEFCON Matrix",
    techStack: "Threat Engine / IP Tables",
    details: "Permite cambiar con un toque el perfil de seguridad del dispositivo. En DEFCON 1, el nodo apaga mDNS, activa rotación de direcciones MAC en BLE y purga metadatos temporales.",
    latency: "< 10ms",
    encryption: "DEFCON Policies"
  },
  {
    id: "blackout",
    name: "Simulador Apagón Blackout",
    category: "Ciberdefensa",
    icon: "⚡",
    summary: "Prueba de estrés que desconecta Internet para validar la conmutación ad-hoc.",
    badge: "Disaster Ready",
    techStack: "Network Isolator",
    details: "Herramienta de simulación que apaga los sockets IP y fuerza a la aplicación a operar exclusivamente con radios de hardware para certificar la resiliencia en simulacros de emergencia.",
    latency: "< 5ms",
    encryption: "N/A"
  },
  {
    id: "dms",
    name: "Hombre Muerto (Dead Man's Switch)",
    category: "Ciberdefensa",
    icon: "💀",
    summary: "Temporizador de seguridad que emite una baliza SOS o destruye las claves.",
    badge: "Fail-Safe",
    techStack: "Keystore Purge / AlarmManager",
    details: "Si el usuario no interactúa con la aplicación antes de que expire la cuenta regresiva configurada, el sistema transmite automáticamente su última ubicación conocida o destruye la bóveda.",
    latency: "< 100ms",
    encryption: "Auto-Purge Keystore"
  },
  {
    id: "security",
    name: "Seguridad Zero-Trust",
    category: "Ciberdefensa",
    icon: "🛡️",
    summary: "FLAG_SECURE anti-capturas, PIN de pánico con autodestrucción y bóveda señuelo configurable.",
    badge: "Anti-Coercion",
    techStack: "Android Keystore / Wipe Engine",
    details: "Protecciones activas contra coerción física: ingresar el PIN de pánico borra instantáneamente todos los datos; ingresar el PIN señuelo configurado abre una sesión falsa aparentemente normal.",
    latency: "< 50ms",
    encryption: "Hardware Keystore TEE"
  },

  // 5. Emergencias, Salud & Rescate (5)
  {
    id: "vitalScan",
    name: "Signos Vitales & Triaje START",
    category: "Emergencias & Salud",
    icon: "🫀",
    summary: "Protocolo médico de triaje de catástrofes con clasificación por colores y registro masivo.",
    badge: "Medical START",
    techStack: "START Algorithm / Offline DB",
    details: "Guía paso a paso al rescatista para clasificar a los heridos en Rojo (Inmediato), Amarillo (Diferido), Verde (Leve) o Negro (Fallecido) y sincroniza las estadísticas por la malla.",
    latency: "< 20ms",
    encryption: "Bóveda Médica Cifrada"
  },
  {
    id: "survivalBeacon",
    name: "Baliza Ultrasonido SOS",
    category: "Emergencias & Salud",
    icon: "🚨",
    summary: "Emisión de socorro acústico FSK inaudible capaz de ser captada en la oscuridad.",
    badge: "SoundMesh SOS",
    techStack: "AudioContext 18.5kHz FSK",
    details: "Emite un tono acústico continuo modulado que otros teléfonos en el área captan para localizar personas atrapadas bajo escombros o en zonas sin señal de radio convencional.",
    latency: "< 300ms",
    encryption: "FSK 18.5kHz Packet"
  },
  {
    id: "amber",
    name: "Sistema Alerta AMBER",
    category: "Emergencias & Salud",
    icon: "🟠",
    summary: "Difusión comunitaria urgente de personas desaparecidas con fotografía geocercada.",
    badge: "Civil Defense",
    techStack: "Geo-Broadcast Mesh",
    details: "Permite difundir alertas de personas extraviadas a todos los dispositivos dentro de un radio geográfico específico, adjuntando fotografía comprimida y descripción física.",
    latency: "< 150ms",
    encryption: "Ed25519 Signed Beacon"
  },
  {
    id: "dms_emergency",
    name: "Alerta Hombre Muerto Rescate",
    category: "Emergencias & Salud",
    icon: "💀",
    summary: "Monitoreo de inactividad para brigadistas en zonas de derrumbe o radiación.",
    badge: "First Responders",
    techStack: "Sensor Inactivity Ping",
    details: "Detecta si el brigadista ha permanecido inmóvil durante un periodo anormal mediante el acelerómetro y emite una alerta acústica y de radio a sus compañeros de escuadrón.",
    latency: "< 50ms",
    encryption: "Mesh Alert Protocol"
  },
  {
    id: "emergencyGlossary",
    name: "Glosario Médico Offline",
    category: "Emergencias & Salud",
    icon: "📖",
    summary: "Enciclopedia de primeros auxilios y protocolos de torniquetes, RCP y fracturas 100% sin red.",
    badge: "Knowledge Base",
    techStack: "IndexedDB / Vector Glossary",
    details: "Base de conocimientos médicos de emergencia optimizada para consulta instantánea durante cortes de energía y catástrofes naturales con instrucciones paso a paso.",
    latency: "< 10ms",
    encryption: "N/A"
  },

  // 6. Inteligencia Artificial Neuronal (2)
  {
    id: "aiCopilot",
    name: "Copiloto IA Offline",
    category: "IA Neuronal",
    icon: "🤖",
    summary: "Inferencia local en dispositivo (Rust / WASM) con RAG semántico (<120ms).",
    badge: "Local LLM / RAG",
    techStack: "ONNX Runtime / WASM / Embeddings",
    details: "Motor de inteligencia artificial embebido en el cliente que procesa lenguaje natural y responde dudas complejas sin enviar ni un solo byte a servidores en la nube.",
    latency: "< 120ms",
    encryption: "On-Device Inference"
  },
  {
    id: "guardian",
    name: "Guardian IA (Firewall S4)",
    category: "IA Neuronal",
    icon: "🛡️",
    summary: "Inspección local previa al cifrado con distancia Hamming 64-bit contra contenido ilícito.",
    badge: "Edge Firewall",
    techStack: "Hamming 64-bit / Toxic-BERT",
    details: "Firewall de contenido en el borde que analiza el texto y las imágenes antes de que sean encriptadas para evitar que la red soberana sea utilizada para explotación infantil o violencia.",
    latency: "< 15ms",
    encryption: "Hamming 64-bit Filter"
  },

  // 7. Herramientas, Sistema & Camuflaje (7)
  {
    id: "settings",
    name: "Ajustes & Personalización",
    category: "Sistema & Herramientas",
    icon: "⚙️",
    summary: "Control granular de identidades, radios habilitadas, temas visuales y cuotas.",
    badge: "Settings Hub",
    techStack: "LocalStorage / Zustand",
    details: "Panel de control maestro para ajustar los parámetros de red malla, la sensibilidad del radar, el tiempo de expiración de mensajes y los perfiles de consumo de energía.",
    latency: "< 5ms",
    encryption: "Local Vault"
  },
  {
    id: "updater",
    name: "Actualizador de Software (OTA)",
    category: "Sistema & Herramientas",
    icon: "🚀",
    summary: "Distribución de actualizaciones de software de nodo a nodo a través de la malla.",
    badge: "Mesh OTA",
    techStack: "Chunked Binary Gossipsub",
    details: "Permite a los usuarios actualizar la aplicación recibiendo los fragmentos binarios firmados criptográficamente de otros usuarios cercanos sin depender de Google Play Store.",
    latency: "P2P Chunked",
    encryption: "Ed25519 Binary Signature"
  },
  {
    id: "health",
    name: "Diagnóstico Salud Sistema",
    category: "Sistema & Herramientas",
    icon: "📊",
    summary: "Telemetría en tiempo real de consumo de memoria, latencia de hilos Rust y FPS.",
    badge: "Diagnostics",
    techStack: "Performance API / Rust NDK",
    details: "Monitor de rendimiento que audita los hilos del motor nativo Rust, el uso de memoria RAM, el estado de las colas de paquetes y la velocidad de fotogramas del renderizador.",
    latency: "< 16ms",
    encryption: "N/A"
  },
  {
    id: "nodeLogs",
    name: "Logs del Nodo Rust SSE",
    category: "Sistema & Herramientas",
    icon: "📋",
    summary: "Consola de eventos en streaming directo desde el socket HTTP /api/events.",
    badge: "SSE Stream",
    techStack: "EventSource / Axum",
    details: "Terminal de registro en tiempo real que transmite los eventos internos de LibP2P, handshakes Bluetooth LE y operaciones de base de datos transaccional Sled directamente a la pantalla.",
    latency: "< 10ms",
    encryption: "Local Loopback"
  },
  {
    id: "calculator",
    name: "Calculadora Señuelo",
    category: "Sistema & Herramientas",
    icon: "🧮",
    summary: "Interfaz camuflada completamente funcional de calculadora científica para ocultar la app.",
    badge: "Stealth Mode",
    techStack: "Math Parser / Decoy Router",
    details: "Transforma la interfaz en una calculadora matemática real. Si un inspector ingresa una operación aritmética, la calcula; solo al ingresar el código secreto se accede a la bóveda RED.",
    latency: "< 5ms",
    encryption: "Stealth Sandbox"
  },
  {
    id: "secReport",
    name: "Reporte Auditoría Seguridad",
    category: "Sistema & Herramientas",
    icon: "📑",
    summary: "Generador de informes técnicos de cumplimiento criptográfico y aislamiento de memoria.",
    badge: "Compliance",
    techStack: "Security Inspector",
    details: "Audita y califica el estado de endurecimiento del terminal, verificando la presencia de FLAG_SECURE, el estado del chip de hardware Keystore y la entropía del generador de números aleatorios.",
    latency: "< 50ms",
    encryption: "Audit Signatures"
  },
  {
    id: "zeroTrust",
    name: "Políticas Zero-Trust",
    category: "Sistema & Herramientas",
    icon: "🛡️",
    summary: "Consent-first en contactos, aislamiento de procesos y rotación obligatoria de claves.",
    badge: "Zero-Trust",
    techStack: "Consent Manager",
    details: "Establece las reglas de autorización estricta: ninguna transmisión de datos es aceptada sin verificación previa de identidad y confirmación humana explícita.",
    latency: "< 10ms",
    encryption: "Zero-Trust Engine"
  },

  // 8. Interoperabilidad & Táctica de Vanguardia (7)
  {
    id: "cursorOnTarget",
    name: "Interoperabilidad ATAK CoT",
    category: "Interoperabilidad & Táctica",
    icon: "🎯",
    summary: "Motor XML Cursor-on-Target (CoT v2.0) y simbología militar OTAN MIL-STD-2525D.",
    badge: "DoD / ATAK CoT",
    techStack: "CursorOnTargetEngine / XML v2.0",
    details: "Serializa y analiza tramas CoT para interoperar sin fricción con terminales ATAK, CivTAK y WinTAK sobre mallas locales y enlaces LoRa de largo alcance con Blue-Force Tracking.",
    latency: "< 15ms",
    encryption: "CoT Signed XML / TLS"
  },
  {
    id: "loraMeshtasticBridge",
    name: "Puente LoRa Meshtastic",
    category: "Interoperabilidad & Táctica",
    icon: "📻",
    summary: "Adaptador físico Semtech SX1262 / ESP32 con encuadre 0x94 C3 y Voz Vocoder.",
    badge: "Semtech SX1262",
    techStack: "WebSerial / BLE SPP / Port 64 Voice",
    details: "Puente Plug & Play con módulos Heltec V3, T-Beam y RAK Wireless. Permite enviar ráfagas de voz comprimida a 1.2 kbps en puerto 64 y tramas de malla PQC en puerto 65.",
    latency: "< 120ms",
    encryption: "Port 65 PQC Encapsulation"
  },
  {
    id: "cbrnRadiationCmos",
    name: "Detector Radiológico CMOS",
    category: "Interoperabilidad & Táctica",
    icon: "☢️",
    summary: "Detección de radiación ionizante (rayos gamma y partículas beta) en el sensor de cámara.",
    badge: "CBRN Sensor",
    techStack: "Canvas Pixel Noise / Poisson Math",
    details: "Mide el flujo de partículas de alta energía que impactan la matriz de silicio CMOS de la cámara con la lente bloqueada, estimando la tasa de dosis ambiental en microsieverts por hora (µSv/h).",
    latency: "< 100ms",
    encryption: "Local Hardware Telemetry"
  },
  {
    id: "opticalRppgTriage",
    name: "Triaje Óptico START & rPPG",
    category: "Interoperabilidad & Táctica",
    icon: "💓",
    summary: "Fotopletismografía remota sin contacto para frecuencia cardíaca y triaje START masivo.",
    badge: "Optical rPPG",
    techStack: "Green Channel FFT / START Algorithm",
    details: "Detecta micro-variaciones en la absorción de luz en los capilares faciales para estimar el pulso cardíaco en segundos y clasificar víctimas de emergencia según el protocolo START.",
    latency: "< 250ms",
    encryption: "On-Device Biometrics"
  },
  {
    id: "ballistics4Dof",
    name: "Calculador Balístico 4DOF",
    category: "Interoperabilidad & Táctica",
    icon: "🎯",
    summary: "Cálculo de trayectorias balísticas con arrastre G1/G7, cota barométrica y viento cruzado.",
    badge: "4DOF Physics",
    techStack: "Runge-Kutta RK4 / Atmospheric Math",
    details: "Solucionador de tiro de precisión que compensa caída de proyectil, deriva por viento, efecto Coriolis y densidad del aire barométrica para operaciones de rescate y seguridad perimetral.",
    latency: "< 5ms",
    encryption: "Air-Gapped Math"
  },
  {
    id: "soundMeshAcoustic",
    name: "Módem Acústico SoundMesh",
    category: "Interoperabilidad & Táctica",
    icon: "🔊",
    summary: "Transmisión de datos por ultrasonido (18.5–20.5 kHz) para aislamiento electromagnético.",
    badge: "Air-Gap Ultrasonic",
    techStack: "WebAudio API / FSK Modulation",
    details: "Modula paquetes binarios en tonos acústicos inaudibles para transferir claves y coordenadas entre dispositivos cercanos sin emitir señales de radiofrecuencia detectables.",
    latency: "< 350ms",
    encryption: "SoundMesh ChaCha20"
  },
  {
    id: "depinPaymentRails",
    name: "DePIN Rails & Sovereign Apps",
    category: "Interoperabilidad & Táctica",
    icon: "⚡",
    summary: "Pasarela multi-riel (Polygon, Lightning, PayPal, Vouchers) y micro-apps descentralizadas.",
    badge: "DePIN SDK",
    techStack: "RedSDKBridge / Sandboxed IFrames",
    details: "Entorno de ejecución aislado para mini-aplicaciones comunitarias (Bazaar, MeshWiki, Juegos P2P) con pagos multi-riel y recompensas automáticas Proof-of-Relay para nodos repetidores.",
    latency: "< 20ms",
    encryption: "Capability-based Sandboxing"
  }
];
