import { TacticalModule } from './types';

export const TACTICAL_MODULES_CATALOG: TacticalModule[] = [
  // ── 1. C4ISR & NAVEGACIÓN TÁCTICA (12 MÓDULOS) ──────────────────────────────
  {
    id: "nodemap",
    name: "Mapa Táctico C4ISR & Blue-Force",
    category: "C4ISR & Navegación Táctica",
    icon: "🗺️",
    summary: "Cartografía táctica offline con renderizado vectorial de rutas multi-salto y seguimiento de fuerzas amigas.",
    badge: "Blue-Force Tracking",
    techStack: "Leaflet / TacticalLocationEngine / Vector Tiles",
    details: "Muestra la posición geográfica precisa de cada nodo del escuadrón en mapas satelitales precargados en caché local sin conexión. Traza líneas de enlace multi-salto con código de color según el RSSI y proyecta conos de visión basados en rumbo dinámico.",
    latency: "< 25ms",
    encryption: "Bóveda Local Cifrada Sled / Ed25519"
  },
  {
    id: "offGridCompass",
    name: "Radar Topográfico GPS & Azimut P2P",
    category: "C4ISR & Navegación Táctica",
    icon: "🧭",
    summary: "Brújula militar off-grid con cálculo matemático azimutal y distancia euclidiana hacia nodos de patrulla.",
    badge: "Geometría Esférica",
    techStack: "Haversine / Magnetometer API / Sensor Fusion",
    details: "Calcula de forma puramente matemática la trayectoria azimutal y distancia esférica hacia cada miembro de la patrulla utilizando coordenadas GNSS embebidas en los handshakes de radio, sin mapas ni conexión a servidores externos.",
    latency: "< 15ms",
    encryption: "Cifrado Geocercado ChaCha20"
  },
  {
    id: "tacticalCompass",
    name: "Brújula Táctica Magnética & Declinación",
    category: "C4ISR & Navegación Táctica",
    icon: "🧭",
    summary: "Magnetómetro triaxial con compensación de inclinación (pitch & roll) y corrección de declinación WMM.",
    badge: "WMM2025 Correction",
    techStack: "Tilt-Compensated Math / World Magnetic Model",
    details: "Brújula digital de precisión balística que compensa la inclinación del terminal hasta 60 grados y aplica la declinación magnética local según el modelo World Magnetic Model (WMM) para obtener el Norte Verdadero geográfico.",
    latency: "< 10ms",
    encryption: "Local Hardware Telemetry"
  },
  {
    id: "celestialPdr",
    name: "Navegación Celestial & PDR Dead-Reckoning",
    category: "C4ISR & Navegación Táctica",
    icon: "⭐",
    summary: "Orientación astronómica por efemérides solares/estelares y navegación por estima de pasos (PDR).",
    badge: "GPS-Denied Navigation",
    techStack: "PedestrianDeadReckoningEngine / Celestial Ephemeris",
    details: "Permite navegar en ambientes con denegación total de GNSS (túneles, búnkeres o jamming de guerra electrónica). El motor PDR detecta pasos, longitud de zancada y azimut cinemático, mientras las efemérides astronómicas calculan la posición por la elevación del sol o estrellas.",
    latency: "< 20ms",
    encryption: "Air-Gapped Math"
  },
  {
    id: "cursorOnTarget",
    name: "Interoperabilidad ATAK / CivTAK CoT v2.0",
    category: "C4ISR & Navegación Táctica",
    icon: "🎯",
    summary: "Motor XML Cursor-on-Target e intercambio bidireccional de tramas tácticas MIL-STD-2525D.",
    badge: "DoD / ATAK CoT",
    techStack: "CursorOnTargetEngine / XML v2.0 / Multicast UDP",
    details: "Serializa y analiza tramas CoT para interoperar sin fricción con terminales ATAK, CivTAK y WinTAK sobre mallas locales y enlaces LoRa de largo alcance con simbología militar OTAN estandarizada.",
    latency: "< 15ms",
    encryption: "CoT Signed XML / TLS"
  },
  {
    id: "ballistics4Dof",
    name: "Calculador Balístico 4DOF & Barometría",
    category: "C4ISR & Navegación Táctica",
    icon: "🎯",
    summary: "Solucionador balístico 4 grados de libertad con arrastre G1/G7, compensación barométrica y viento cruzado.",
    badge: "4DOF Physics",
    techStack: "Runge-Kutta RK4 / Atmospheric Math / Barometer API",
    details: "Calcula curvas de caída de proyectil, deriva por viento, efecto Coriolis y densidad del aire barométrica en tiempo real para operaciones de rescate, seguridad perimetral y tiro de precisión sin internet.",
    latency: "< 5ms",
    encryption: "Air-Gapped Math"
  },
  {
    id: "tacticalFoxhunt",
    name: "Caza de Señales RF & Radiogoniometría",
    category: "C4ISR & Navegación Táctica",
    icon: "🦊",
    summary: "Radiogoniometría táctica (RDF) para triangulación y localización de balizas hostiles o víctimas perdidas.",
    badge: "RDF Triangulation",
    techStack: "Doppler Math / RSSI Bearing Gradient / Kalman",
    details: "Guía al rescatista o patrulla hacia la fuente de emisión de radio midiendo gradientes de potencia RSSI conforme el operador se desplaza, triangulando la posición del transmisor mediante intersección geométrica.",
    latency: "< 35ms",
    encryption: "RSSI Directional Gradient"
  },
  {
    id: "sonarSeismic",
    name: "Sismógrafo Táctico & Detección Geofónica",
    category: "C4ISR & Navegación Táctica",
    icon: "🌋",
    summary: "Detección de vibraciones corticales, colapso de estructuras y movimiento de maquinaria pesada.",
    badge: "Seismic Geophone",
    techStack: "Triaxial Accelerometer FFT / Low-Frequency DSP",
    details: "Convierte el acelerómetro del dispositivo en un geófono de alta sensibilidad que detecta micro-vibraciones en el suelo, advirtiendo de derrumbes inminentes o paso de vehículos en áreas de desastre.",
    latency: "< 12ms",
    encryption: "Local Hardware Telemetry"
  },
  {
    id: "canvas",
    name: "Canvas Táctico Colaborativo P2P",
    category: "C4ISR & Navegación Táctica",
    icon: "🎨",
    summary: "Pizarra operacional interactiva con sincronización vectorial de trazos y simbología en tiempo real.",
    badge: "Zero-Server CRDT",
    techStack: "CRDT Vectorial / WebRTC DataChannel",
    details: "Mesa de operaciones visual donde brigadas y comandantes dibujan perímetros, rutas de evacuación y zonas calientes con sincronización vectorial instantánea punto a punto sin servidores intermedios.",
    latency: "< 30ms",
    encryption: "WebRTC DTLS / SRTP"
  },
  {
    id: "liveStream",
    name: "Streaming de Video Táctico WebRTC Mesh",
    category: "C4ISR & Navegación Táctica",
    icon: "📺",
    summary: "Transmisión de vídeo en vivo P2P de ultra-baja latencia con señalización descentralizada.",
    badge: "WebRTC Mesh",
    techStack: "H.264 / WebRTC DataChannel Mesh",
    details: "Streaming de vídeo punto a punto o retransmitido por nodos repetidores. Diseñado para reconocimiento aéreo con drones o monitoreo de perímetros en zonas de emergencia sin conectividad celular.",
    latency: "< 250ms",
    encryption: "DTLS 1.3 / ChaCha20"
  },
  {
    id: "weather",
    name: "Meteorología Táctica CAP & Barómetro",
    category: "C4ISR & Navegación Táctica",
    icon: "🌤️",
    summary: "Alertas meteorológicas CAP y predicción de tormentas severas mediante gradiente barométrico.",
    badge: "Sensor Barométrico",
    techStack: "CAP XML / Pressure Sensor / Atmospheric Trend",
    details: "Monitorea continuamente la presión atmosférica del sensor barométrico para predecir frentes de tormenta o huracanes antes de que ocurran, difundiendo alertas de protocolo CAP a la comunidad.",
    latency: "< 10ms",
    encryption: "Firma Digital CAP"
  },
  {
    id: "tacticalCadViewer",
    name: "Visor CAD Táctico Vectorial & Plano 4 Capas",
    category: "C4ISR & Navegación Táctica",
    icon: "📐",
    summary: "Renderizado técnico interactivo SVG 4K offline de la arquitectura física y lógica del sistema.",
    badge: "4K CAD Architecture",
    techStack: "React 19 Vectorial / SVG CAD / Pan-Zoom",
    details: "Permite inspeccionar en alta fidelidad los esquemas de interconexión entre las 4 capas del sistema, el bus de eventos y la topología de red con atajos tácticos y retículas HUD.",
    latency: "< 16ms (60 FPS)",
    encryption: "Local Offline Render"
  },

  // ── 2. COMUNICACIONES CUÁNTICAS & MALLA SOBERANA (14 MÓDULOS) ──────────────
  {
    id: "channels",
    name: "Canales Mesh Gossipsub & Tópicos",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "📻",
    summary: "Subcanales temáticos de escuadrón (#general, #sos, #logistica) sobre broadcast Gossipsub.",
    badge: "Multi-Topic Gossipsub",
    techStack: "Rust Mesh Kernel / Sled DB / LibP2P",
    details: "Permite la creación de salas de mensajería efímeras o persistentes por temas dentro del rango de radio de la malla local. Los mensajes son propagados por todos los nodos cercanos y deduplicados por 72 horas.",
    latency: "< 45ms",
    encryption: "Noise XK + ChaCha20-Poly1305"
  },
  {
    id: "walkie",
    name: "Walkie-Talkie Push-To-Talk (PTT)",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "🎙️",
    summary: "Canal de voz militar PTT con compresión de 1.2-3.2 kbps y auto-reproducción instantánea en escuadrón.",
    badge: "Ultra-Low Bitrate",
    techStack: "LowBitrateVocoder / IMA-ADPCM / PTT DSP",
    details: "Canal de radio por voz full-duplex optimizado para rescate o coordinación táctica. Al presionar el botón PTT, la voz se comprime a 1.2 kbps y se auto-reproduce instantáneamente en los terminales del escuadrón.",
    latency: "< 90ms",
    encryption: "ChaCha20-Poly1305 Audio"
  },
  {
    id: "broadcast",
    name: "Difusión Privada & Alertas Cerradas",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "📢",
    summary: "Emisión unidireccional de boletines urgentes cifrados a listas cerradas de contactos autorizados.",
    badge: "Cifrado E2E",
    techStack: "ChaCha20-Poly1305 / Ephemeral Epk",
    details: "Emite comunicados urgentes o boletines a múltiples destinatarios pre-aprobados de forma simultánea, cifrando cada paquete individualmente para garantizar la privacidad de los miembros de la lista.",
    latency: "< 60ms",
    encryption: "Double Ratchet E2E"
  },
  {
    id: "socialFeed",
    name: "Feed Social Descentralizado DTN",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "🌍",
    summary: "Muro de publicaciones públicas descentralizadas propagadas mediante mulas de datos DTN Sneakernet.",
    badge: "DTN Sneakernet",
    techStack: "Ed25519 Signed Payloads / Merkle Tree",
    details: "Red social resistente a censura donde cada publicación está firmada por la clave privada Ed25519 del autor y viaja de dispositivo en dispositivo mediante saltos oportunistas sin servidores centrales.",
    latency: "Asíncrono DTN",
    encryption: "Ed25519 / Merkle Tree"
  },
  {
    id: "pqcCrypto",
    name: "Bóveda Criptográfica Post-Cuántica ML-KEM",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "🔐",
    summary: "Criptografía híbrida post-cuántica ML-KEM-768 (FIPS 203) combinada con Signal Double Ratchet.",
    badge: "ML-KEM-768",
    techStack: "ML-KEM-768 / Noise XK / X25519",
    details: "Combina el estándar de encapsulamiento en retículos ML-KEM-768 con el protocolo Signal Double Ratchet para blindar todas las conversaciones contra futuras computadoras cuánticas (Harvest Now, Decrypt Later).",
    latency: "< 12ms",
    encryption: "ML-KEM-768 ⊕ X25519"
  },
  {
    id: "loraMeshtasticBridge",
    name: "Puente LoRa Meshtastic SX1262",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "📻",
    summary: "Adaptador físico Semtech SX1262 con encuadre 0x94 C3, puerto 64 de voz y puerto 65 PQC.",
    badge: "Semtech SX1262",
    techStack: "WebSerial / BLE SPP / Port 64 Voice / Port 65 PQC",
    details: "Puente Plug & Play con módulos Heltec V3, T-Beam y RAK Wireless. Permite enviar ráfagas de voz comprimida a 1.2 kbps en puerto 64 y tramas de malla PQC en puerto 65 a distancias de más de 15 km.",
    latency: "< 120ms",
    encryption: "Port 65 PQC Encapsulation"
  },
  {
    id: "loraTransceiver",
    name: "Transceptor LoRa Nativo de Largo Alcance",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "📡",
    summary: "Manejo directo de capa física LoRa en bandas US915 / EU868 / 433MHz con spreading factor dinámico.",
    badge: "Long-Range RF",
    techStack: "Semtech SX1262 / SPI / UART HAL / SF7-SF12",
    details: "Controlador de bajo nivel para enlaces de ultra-largo alcance con modulación de espectro ensanchado (Chirp Spread Spectrum). Modula automáticamente el Spreading Factor de SF7 a SF12 según el SNR del enlace.",
    latency: "< 180ms",
    encryption: "Hardware AES-128 / PQC Port"
  },
  {
    id: "soundMeshAcoustic",
    name: "Módem Acústico Ultrasonido SoundMesh",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "🔊",
    summary: "Transmisión de datos por ultrasonido (18.5–20.5 kHz) para aislamiento electromagnético estricto.",
    badge: "Air-Gap Ultrasonic",
    techStack: "WebAudio API / FSK Modulation / DSP Filter",
    details: "Modula paquetes binarios en tonos acústicos inaudibles para transferir claves, coordenadas y mensajes de texto entre dispositivos cercanos sin emitir señales de radiofrecuencia detectables.",
    latency: "< 350ms",
    encryption: "SoundMesh ChaCha20"
  },
  {
    id: "network",
    name: "Topología Kademlia DHT & Túneles DCUtR",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "🌐",
    summary: "Grafo interactivo de enrutamiento Kademlia DHT, tabla de pares y evasión de NATs celulares.",
    badge: "DHT Routing",
    techStack: "LibP2P Kademlia / Axum SSE / DCUtR Hole-Punching",
    details: "Permite inspeccionar visualmente la tabla de enrutamiento XOR de Kademlia, los árboles de suscripción Gossipsub y los túneles DCUtR de evasión de NATs simétricos celulares.",
    latency: "< 25ms",
    encryption: "LibP2P SecIO / Noise"
  },
  {
    id: "nearby",
    name: "Radar Hardware BLE / Wi-Fi Direct Raw",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "📡",
    summary: "Escaneo en tiempo real de potencia RSSI, estado de batería y paquetes recibidos sin emparejamiento.",
    badge: "Raw Radio Stack",
    techStack: "BLE GATT HCI / Wi-Fi Direct Sniffer",
    details: "Monitorea continuamente el espectro electromagnético cercano para detectar balizas de presencia de otros terminales RED, midiendo la intensidad de señal de -30 dBm (contacto cercano) a -95 dBm (límite).",
    latency: "< 100ms",
    encryption: "HMAC Blind Beacon"
  },
  {
    id: "loraTdmaScheduler",
    name: "Planificador LoRa TDMA Determinista",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "⏱️",
    summary: "Supertrama periódica de 2000 ms (10 slots de 200 ms) con hash FNV-1a y contienda CSMA/CA.",
    badge: "TDMA Anti-Colisión",
    techStack: "LoRaTdmaSchedulerEngine / FNV-1a / CSMA-CA",
    details: "Erradica colisiones en concentraciones masivas dividiendo el tiempo en ranuras deterministas asignadas por identidad digital. Slot 8 para balizas de red, Slot 9 para contienda y bypass instantáneo para emergencias SOS.",
    latency: "< 200ms",
    encryption: "RED Header v2 / Poly1305"
  },
  {
    id: "geohashSpatialRouting",
    name: "Enrutamiento Espacial Geohash DTN",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "📍",
    summary: "Indexación espacial en IndexedDB v2 y poda de paquetes según el vector geográfico del portador.",
    badge: "Geohash Pruning",
    techStack: "GeohashSpatialRouting / IndexedDB v2 / Base32",
    details: "Previene la saturación transcontinental de colas de almacenamiento en mulas de datos móviles y satélites LEO, filtrando mensajes mediante cuadrantes Geohash (resolución 4 regional vs 6 táctica) y distancias Manhattan.",
    latency: "DTN Espacial",
    encryption: "Target Geohash Index"
  },
  {
    id: "esp32SolarRepeater",
    name: "Repetidor Solar Autónomo ESP32-S3",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "☀️",
    summary: "Firmware open-source de campo para Heltec WiFi LoRa 32 V3 con filtro de Bloom de 2048 bits.",
    badge: "Repetidor Autónomo",
    techStack: "ESP32-S3 / Semtech SX1262 / RadioLib / PlatformIO",
    details: "Estación de relevo permanente para cimas y tejados alimentada por panel solar 5V y celda 18650 (~$15-20 USD BOM). Opera a 80 MHz con consumo centinela <12 mA y deduplicación en memoria volátil de alta velocidad.",
    latency: "< 150ms",
    encryption: "RED Wire Format v2"
  },
  {
    id: "leoSatelliteGateway",
    name: "Pasarela Satelital LEO Downlink",
    category: "Comunicaciones Cuánticas & Malla",
    icon: "🛰️",
    summary: "Enlace Store-and-Forward orbital con filtrado espacial de huella terrestre para descarga en ráfaga.",
    badge: "Orbital Gateway",
    techStack: "SatelliteMeshGatewayEngine / SGP4 / Footprint Pruning",
    details: "Calcula pases de constelaciones de satélites en órbita baja y sincroniza la retransmisión de balizas y mensajes críticos únicamente sobre su huella geográfica de cobertura terrestre.",
    latency: "Pase Orbital",
    encryption: "AEAD Downlink"
  },

  // ── 3. CIBERDEFENSA & GUERRA ELECTRÓNICA (9 MÓDULOS) ─────────────────────────
  {
    id: "globalShield",
    name: "Escudo Global & Matriz DEFCON 5-1",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🛡️",
    summary: "Matriz táctica de niveles de amenaza (DEFCON 5 a 1) que endurece progresivamente las radios.",
    badge: "DEFCON Matrix",
    techStack: "Threat Engine / IP Tables / Radio Governance",
    details: "Permite cambiar con un toque el perfil de seguridad del dispositivo. En DEFCON 1, el nodo apaga mDNS, activa rotación de direcciones MAC en BLE cada 15 minutos y purga metadatos temporales de memoria.",
    latency: "< 10ms",
    encryption: "DEFCON Hardened Policies"
  },
  {
    id: "rfSpectrum",
    name: "Analizador Espectro RF & Alerta EW",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🛡️",
    summary: "Detección de interferencias electrónicas (EW jamming) y análisis de piso de ruido en 2.4GHz / 915MHz.",
    badge: "Anti-Jamming EW",
    techStack: "RSSI Variance / Spectral DSP / Channel Hopping",
    details: "Analiza la varianza y piso de ruido del receptor de radio. Si detecta un ataque de denegación de espectro (Jammer), conmuta automáticamente los paquetes al canal ultrasónico SoundMesh o LoRa.",
    latency: "< 15ms",
    encryption: "Frequency Hopping Spread Spectrum"
  },
  {
    id: "acousticWarfare",
    name: "Guerra Acústica & Contramedidas de Audio",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🔇",
    summary: "Generador de ruido blanco ultrasónico para anulación de micrófonos espía y detección de escuchas.",
    badge: "Mic Jammer",
    techStack: "Ultrasonic Intermodulation / Audio DSP",
    details: "Emite patrones de ultrasonido modulados que saturan físicamente las membranas de micrófonos de escucha ambiental sin molestar al oído humano, protegiendo reuniones tácticas confidenciales.",
    latency: "< 5ms",
    encryption: "Acoustic White Noise"
  },
  {
    id: "blackout",
    name: "Simulador Apagón Total Blackout",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "⚡",
    summary: "Prueba de estrés que desconecta Internet y telefonía para validar la conmutación ad-hoc autónoma.",
    badge: "Disaster Ready",
    techStack: "Network Isolator / Stress-Test Harness",
    details: "Herramienta de simulación que apaga los sockets IP y fuerza a la aplicación a operar exclusivamente con radios de hardware para certificar la resiliencia en simulacros de emergencia.",
    latency: "< 5ms",
    encryption: "N/A"
  },
  {
    id: "dms",
    name: "Hombre Muerto (Dead Man's Switch)",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "💀",
    summary: "Temporizador de seguridad que emite una baliza SOS o destruye las claves si el usuario queda incapacitado.",
    badge: "Fail-Safe",
    techStack: "Keystore Purge / AlarmManager / Accelerometer",
    details: "Si el usuario no interactúa con la aplicación antes de que expire la cuenta regresiva configurada, el sistema transmite automáticamente su última ubicación conocida o destruye la bóveda criptográfica.",
    latency: "< 100ms",
    encryption: "Auto-Purge Keystore TEE"
  },
  {
    id: "security",
    name: "Seguridad Militar Zero-Trust & Anti-Forense",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🛡️",
    summary: "FLAG_SECURE anti-capturas, PIN de pánico con autodestrucción y bóveda señuelo configurable.",
    badge: "Anti-Coercion",
    techStack: "Android Keystore / Wipe Engine / TEE",
    details: "Protecciones activas contra coerción física: ingresar el PIN de pánico borra instantáneamente todos los datos; ingresar el PIN señuelo abre una sesión falsa aparentemente normal.",
    latency: "< 50ms",
    encryption: "Hardware Keystore TEE"
  },
  {
    id: "calculator",
    name: "Calculadora Científica Señuelo Camuflada",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🧮",
    summary: "Interfaz camuflada completamente funcional de calculadora científica para ocultar la aplicación.",
    badge: "Stealth Mode",
    techStack: "Math Parser / Decoy Router / Camouflage Sandbox",
    details: "Transforma la interfaz en una calculadora matemática real. Si un inspector ingresa una operación aritmética, la calcula; solo al ingresar el código secreto se accede a la bóveda RED.",
    latency: "< 5ms",
    encryption: "Stealth Sandbox"
  },
  {
    id: "stegoVault",
    name: "Bóveda Esteganográfica en Imágenes",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🖼️",
    summary: "Ocultamiento de claves privadas y coordenadas dentro de los píxeles menos significativos (LSB).",
    badge: "Anti-Forensics",
    techStack: "LSB Steganography / ChaCha20 Matrix",
    details: "Incrusta datos altamente confidenciales modificando de forma imperceptible los bits menos significativos (LSB) de imágenes JPEG/PNG, haciéndolos invisibles ante escáneres forenses.",
    latency: "< 120ms",
    encryption: "ChaCha20 + LSB Matrix"
  },
  {
    id: "zeroTrust",
    name: "Políticas de Aislamiento & Zero-Trust",
    category: "Ciberdefensa & Guerra Electrónica",
    icon: "🛡️",
    summary: "Consent-first en contactos, aislamiento de procesos y rotación obligatoria de claves de sesión.",
    badge: "Zero-Trust",
    techStack: "Consent Manager / Process Sandbox",
    details: "Establece las reglas de autorización estricta: ninguna transmisión de datos es aceptada sin verificación previa de identidad y confirmación humana explícita.",
    latency: "< 10ms",
    encryption: "Zero-Trust Engine"
  },

  // ── 4. SOPORTE VITAL, CBRN & EMERGENCIAS (9 MÓDULOS) ────────────────────────
  {
    id: "vitalScan",
    name: "Signos Vitales & Triaje Médico START",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "🫀",
    summary: "Protocolo médico de triaje de catástrofes con clasificación por colores y sincronización por malla.",
    badge: "Medical START",
    techStack: "START Algorithm / Offline DB / Mesh Sync",
    details: "Guía paso a paso al rescatista para clasificar a los heridos en Rojo (Inmediato), Amarillo (Diferido), Verde (Leve) o Negro (Fallecido) y sincroniza las estadísticas por la malla.",
    latency: "< 20ms",
    encryption: "Bóveda Médica Cifrada"
  },
  {
    id: "opticalRppgTriage",
    name: "Triaje Óptico START & Fotopletismografía rPPG",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "💓",
    summary: "Fotopletismografía remota sin contacto para pulso cardíaco y frecuencia respiratoria por cámara.",
    badge: "Optical rPPG",
    techStack: "Green Channel FFT / Eulerian Video Mag / START",
    details: "Detecta micro-variaciones en la absorción de luz en los capilares faciales para estimar el pulso cardíaco en segundos y clasificar víctimas de emergencia según el protocolo START sin contacto físico.",
    latency: "< 250ms",
    encryption: "On-Device Biometrics"
  },
  {
    id: "cbrnRadiationCmos",
    name: "Dosímetro Radiológico CMOS Gamma/Beta",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "☢️",
    summary: "Detección de radiación ionizante (rayos gamma y partículas beta) en la matriz de silicio de la cámara.",
    badge: "CBRN Sensor",
    techStack: "Canvas Pixel Noise / Poisson Math / µSv/h Calc",
    details: "Mide el flujo de partículas de alta energía que impactan la matriz de silicio CMOS de la cámara con la lente bloqueada, estimando la tasa de dosis ambiental en microsieverts por hora (µSv/h).",
    latency: "< 100ms",
    encryption: "Local Hardware Telemetry"
  },
  {
    id: "cbrnSatellite",
    name: "Monitor Satelital CBRN & Plumas Tóxicas",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "🛰️",
    summary: "Modelado atmosférico Gaussiano de dispersión de gases tóxicos y partículas radiactivas.",
    badge: "Gaussian Plume",
    techStack: "Gaussian Plume Dispersion / Wind Vector / GeoJSON",
    details: "Calcula y proyecta en el mapa táctico el área de dispersión de fugas químicas, biológicas o radiactivas basándose en la velocidad y dirección del viento y la topografía local.",
    latency: "< 40ms",
    encryption: "Local Vector Model"
  },
  {
    id: "tcccBallistics",
    name: "Protocolo Médico TCCC de Combate & Guía",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "🩹",
    summary: "Guía de atención táctica bajo fuego (TCCC) para control de hemorragias masivas y neumotórax.",
    badge: "TCCC Combat Care",
    techStack: "Tactical Combat Casualty Care / Interactive Decision Tree",
    details: "Árbol de decisiones médicas tácticas para rescatistas bajo fuego o en desastres: aplicación de torniquetes de extremidad, apósitos hemostáticos, descompresión con aguja y manejo de vía aérea.",
    latency: "< 10ms",
    encryption: "N/A"
  },
  {
    id: "survivalBeacon",
    name: "Baliza Ultrasonido SOS Sub-Escombros",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "🚨",
    summary: "Emisión de socorro acústico FSK inaudible de alta penetración para personas atrapadas.",
    badge: "SoundMesh SOS",
    techStack: "AudioContext 18.5kHz FSK / Acoustic Beacon",
    details: "Emite un tono acústico continuo modulado que otros teléfonos en el área captan para localizar personas atrapadas bajo escombros o en zonas sin señal de radio convencional.",
    latency: "< 300ms",
    encryption: "FSK 18.5kHz Packet"
  },
  {
    id: "amber",
    name: "Sistema Alerta AMBER Comunitaria",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "🟠",
    summary: "Difusión comunitaria urgente de personas desaparecidas con fotografía geocercada y reporte.",
    badge: "Civil Defense",
    techStack: "Geo-Broadcast Mesh / Ed25519 Beacon",
    details: "Permite difundir alertas de personas extraviadas a todos los dispositivos dentro de un radio geográfico específico, adjuntando fotografía comprimida y descripción física.",
    latency: "< 150ms",
    encryption: "Ed25519 Signed Beacon"
  },
  {
    id: "dms_emergency",
    name: "Alerta Hombre Muerto Rescate",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "💀",
    summary: "Monitoreo de inactividad cinemática para brigadistas en zonas de derrumbe o radiación.",
    badge: "First Responders",
    techStack: "Sensor Inactivity Ping / Accelerometer Watcher",
    details: "Detecta si el brigadista ha permanecido inmóvil durante un periodo anormal mediante el acelerómetro y emite una alerta acústica y de radio a sus compañeros de escuadrón.",
    latency: "< 50ms",
    encryption: "Mesh Alert Protocol"
  },
  {
    id: "emergencyGlossary",
    name: "Glosario Médico Offline & Primeros Auxilios",
    category: "Soporte Vital, CBRN & Emergencias",
    icon: "📖",
    summary: "Enciclopedia de primeros auxilios y protocolos de torniquetes, RCP y fracturas 100% sin red.",
    badge: "Knowledge Base",
    techStack: "IndexedDB / Vector Glossary / Offline Cache",
    details: "Base de conocimientos médicos de emergencia optimizada para consulta instantánea durante cortes de energía y catástrofes naturales con instrucciones paso a paso e ilustraciones tácticas.",
    latency: "< 10ms",
    encryption: "N/A"
  },

  // ── 5. ECONOMÍA DEPIN, PAGOS & SOBERANÍA DIGITAL (9 MÓDULOS) ────────────────
  {
    id: "commercialHub",
    name: "Hub Comercial & Recompensas DePIN",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "⚡",
    summary: "Economía DePIN de retransmisión: gana tokens $RED por reenviar paquetes ajenos (Proof-of-Relay).",
    badge: "Proof-of-Relay",
    techStack: "Tokenomics / Relay Ledger / Proof-of-Relay",
    details: "Premia a los nodos que sirven como repetidores en zonas remotas. Cada paquete retransmitido exitosamente genera un comprobante de servicio criptográfico canjeable por recompensas en la red.",
    latency: "< 200ms",
    encryption: "Merkle Proof-of-Relay"
  },
  {
    id: "depinPaymentRails",
    name: "Rieles Multi-Pago (Polygon, Lightning, Fiat)",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "⚡",
    summary: "Pasarela multi-riel para liquidación de pagos de servicios y micro-comercio sin internet.",
    badge: "Multi-Rail Pay",
    techStack: "RedSDKBridge / Sandboxed Rails / Smart Contracts",
    details: "Conecta la malla comunitaria con rieles globales de pago (Polygon PoS, Lightning Network Bitcoin y vales fiat) permitiendo el comercio de víveres, combustible y medicinas en emergencias.",
    latency: "< 20ms",
    encryption: "Capability-based Sandboxing"
  },
  {
    id: "p2pPay",
    name: "Pagos & Vouchers P2P Offline",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "💳",
    summary: "Emisión y canje de vales comerciales offline firmados con firmas ciegas Ed25519 con paridad fiat.",
    badge: "Offline Cash",
    techStack: "Ed25519 Blind Signatures / Barter Engine",
    details: "Permite realizar transacciones comerciales durante apagones financieros o cortes de tarjetas. Los vales se transmiten por Bluetooth y se validan mediante firmas ciegas Ed25519 sin banco.",
    latency: "< 80ms",
    encryption: "ChaCha20 / Ed25519"
  },
  {
    id: "web3Vault",
    name: "Bóveda Web3 & Enlace EVM",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "🦊",
    summary: "Firma EIP-712 sin gas y enlace multi-cadena con billeteras descentralizadas en Polygon / Ethereum.",
    badge: "EVM Bridge",
    techStack: "Ethers.js / EIP-712 / Secp256k1",
    details: "Permite vincular tu dirección pública de Ethereum/Polygon a tu identidad soberana did:red para firmar mensajes autenticados y participar en contratos inteligentes descentralizados.",
    latency: "< 150ms",
    encryption: "Secp256k1 / EIP-712"
  },
  {
    id: "idVault",
    name: "Perfil & Bóveda DID Auto-Soberana",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "🪪",
    summary: "Identidad auto-soberana W3C did:red basada en clave pública Ed25519 con QR táctico.",
    badge: "Self-Sovereign",
    techStack: "W3C DID / Ed25519 / Tactical QR",
    details: "Tu identidad digital no pertenece a ninguna empresa ni gobierno. Es un par de claves criptográficas derivadas matemáticamente en tu teléfono, exportable como código QR táctico para emparejamiento.",
    latency: "< 5ms",
    encryption: "Ed25519 / Curve25519"
  },
  {
    id: "explorer",
    name: "Explorador Blockchain de Micro-Cadena",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "⛓️",
    summary: "Auditoría de bloques y transacciones de la cadena de bloques liviana interna del sistema RED.",
    badge: "Micro-Chain",
    techStack: "Merkle Trees / PoS Consensus / BLAKE3",
    details: "Visualizador de la micro-cadena distribuida del ecosistema RED que registra las operaciones críticas de estado, revocaciones de identidad y recompensas de retransmisión sin consumir gigabytes.",
    latency: "< 50ms",
    encryption: "BLAKE3 Merkle DAG / ChaCha20-Poly1305"
  },
  {
    id: "appStore",
    name: "Bazaar de Micro-Apps Descentralizadas",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "🏪",
    summary: "Tienda comunitaria de micro-aplicaciones offline (MeshWiki, Mercado Local, Juegos P2P).",
    badge: "P2P Bazaar",
    techStack: "RedSDKBridge / Sandboxed IFrames / Content Hash",
    details: "Repositorio P2P de mini-aplicaciones que se descargan de nodo en nodo a través de la malla. Las aplicaciones corren en sandboxes aislados con permisos controlados por capacidades criptográficas.",
    latency: "< 15ms",
    encryption: "Subresource Integrity / Sandboxing"
  },
  {
    id: "backup",
    name: "Respaldos & Restauración Hermética",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "💾",
    summary: "Copia de seguridad 1-toque protegida por PIN Maestro con semilla mnemónica BIP-39 y Argon2id.",
    badge: "Zero-Knowledge",
    techStack: "Argon2id / AES-GCM-256 / BIP-39",
    details: "Exporta tu bóveda en un contenedor hermético cifrado con Argon2id. Puedes recuperarla en cualquier dispositivo mediante una frase mnemónica de 12 palabras o archivo cifrado.",
    latency: "< 300ms",
    encryption: "Argon2id / AES-256-GCM"
  },
  {
    id: "webCompanionLink",
    name: "Vincular Dispositivo Web Companion (PC)",
    category: "Economía DePIN, Pagos & Soberanía",
    icon: "💻",
    summary: "Túnel WebRTC cifrado P2P que sincroniza la bóveda entre el celular y el navegador de la PC.",
    badge: "Sync Local",
    techStack: "WebRTC DataChannel / AES-256-GCM / QR Handshake",
    details: "Escanea el código QR de la pantalla de tu computadora desde tu celular Android para establecer un túnel WebRTC cifrado directo en red local sin que los mensajes toquen servidores externos.",
    latency: "< 35ms",
    encryption: "AES-256-GCM / WebRTC DTLS"
  },

  // ── 6. NÚCLEO DE SISTEMA & IA EDGE (9 MÓDULOS) ──────────────────────────────
  {
    id: "aiCopilot",
    name: "Copiloto IA Offline & RAG Semántico",
    category: "Núcleo de Sistema & IA Edge",
    icon: "🤖",
    summary: "Inferencia local en dispositivo (Rust / WASM / ONNX) con RAG semántico (<120ms) sin nube.",
    badge: "Local LLM / RAG",
    techStack: "ONNX Runtime / WASM / Cosine Similarity",
    details: "Motor de inteligencia artificial embebido en el cliente que procesa lenguaje natural, traduce entre idiomas y asiste en diagnósticos de emergencia sin enviar ni un solo byte a servidores en la nube.",
    latency: "< 120ms",
    encryption: "On-Device Inference"
  },
  {
    id: "guardian",
    name: "Guardian IA (Firewall Neuronal S4)",
    category: "Núcleo de Sistema & IA Edge",
    icon: "🛡️",
    summary: "Inspección local previa al cifrado con distancia Hamming 64-bit contra contenido ilícito.",
    badge: "Edge Firewall",
    techStack: "Hamming 64-bit / Toxic-BERT / Local Tokenizer",
    details: "Firewall de contenido en el borde que analiza el texto y las imágenes antes de que sean encriptadas para evitar que la red soberana sea utilizada para explotación infantil o violencia.",
    latency: "< 15ms",
    encryption: "Hamming 64-bit Filter"
  },
  {
    id: "ecoMesh",
    name: "Gobernador Cinemático KineticDutyGovernor",
    category: "Núcleo de Sistema & IA Edge",
    icon: "🔋",
    summary: "Gobernador cinemático de energía que modula los escaneos de radio según el giroscopio y batería.",
    badge: "Ahorro Dinámico",
    techStack: "Battery API / Gyroscope / KineticDutyGovernor",
    details: "Ajusta la tasa de muestreo y escaneo de radio según el movimiento físico y el nivel de batería restante, extendiendo la autonomía del terminal de 24 horas hasta 7 días en operaciones de supervivencia.",
    latency: "Tiempo Real",
    encryption: "N/A"
  },
  {
    id: "swarmHealthHUD",
    name: "HUD de Salud del Enjambre & QoS de Malla",
    category: "Núcleo de Sistema & IA Edge",
    icon: "📊",
    summary: "Telemetría en tiempo real de relación señal/ruido (SNR), RSSI, pérdida de paquetes y latencia RTT.",
    badge: "Swarm Health",
    techStack: "Rust LibP2P Ping / SwarmHealthHUD / Metric Buffer",
    details: "Panel de diagnóstico de misión crítica que audita en vivo la relación señal/ruido (SNR), intensidad de señal de recepción (RSSI), latencia de ida y vuelta (RTT) y tasa de paquetes perdidos de cada salto de la malla.",
    latency: "< 15ms",
    encryption: "Local Hardware Telemetry"
  },
  {
    id: "hyperBrowser",
    name: "Navegador Soberano P2P & Caché Distribuida",
    category: "Núcleo de Sistema & IA Edge",
    icon: "🌐",
    summary: "Navegación web descentralizada que comparte páginas cacheadas y sitios estáticos por la malla.",
    badge: "Distributed Web",
    techStack: "ServiceWorker Cache / Merkle Content Hash / DTN",
    details: "Permite acceder a manuales técnicos, mapas de carreteras y guías de supervivencia almacenadas en la caché distribuida de otros dispositivos cercanos sin conexión a internet.",
    latency: "< 20ms",
    encryption: "SHA-256 Content Addressed"
  },
  {
    id: "shakePair",
    name: "Shake & Pair (Acelerómetro Cinético)",
    category: "Núcleo de Sistema & IA Edge",
    icon: "📳",
    summary: "Emparejamiento criptográfico instantáneo agitando ambos dispositivos mediante sensores físicos.",
    badge: "Hardware Entropy",
    techStack: "Android Sensor API / BLE Scan / Cross-Correlation",
    details: "Agitar dos teléfonos al mismo tiempo genera un vector de entropía cinemática correlacionada por acelerómetro que autentica e intercambia claves públicas de forma física y previene ataques Man-in-the-Middle.",
    latency: "< 500ms",
    encryption: "Sensor Entropy / Ed25519"
  },
  {
    id: "updater",
    name: "Actualizador Binario P2P (Mesh-OTA)",
    category: "Núcleo de Sistema & IA Edge",
    icon: "🚀",
    summary: "Distribución de actualizaciones binarias de nodo a nodo a través de la malla sin Play Store.",
    badge: "Mesh OTA",
    techStack: "Chunked Binary Gossipsub / Ed25519 Verify",
    details: "Permite a los usuarios actualizar la aplicación recibiendo los fragmentos binarios firmados criptográficamente de otros usuarios cercanos sin depender de Google Play Store ni servidores centrales.",
    latency: "P2P Chunked",
    encryption: "Ed25519 Binary Signature"
  },
  {
    id: "health",
    name: "Diagnóstico Salud de Sistema & Hilos Rust",
    category: "Núcleo de Sistema & IA Edge",
    icon: "📊",
    summary: "Telemetría en tiempo real de consumo de memoria, latencia de hilos nativos Rust y FPS.",
    badge: "Diagnostics",
    techStack: "Performance API / Rust NDK / Memory Watcher",
    details: "Monitor de rendimiento que audita los hilos del motor nativo Rust, el uso de memoria RAM, el estado de las colas de paquetes y la velocidad de fotogramas del renderizador para prevenir fugas de recursos.",
    latency: "< 16ms",
    encryption: "N/A"
  },
  {
    id: "nodeLogs",
    name: "Consola de Eventos del Kernel Rust SSE",
    category: "Núcleo de Sistema & IA Edge",
    icon: "📋",
    summary: "Terminal de eventos en streaming directo desde el socket HTTP /api/events del motor Rust.",
    badge: "SSE Stream",
    techStack: "EventSource / Axum / Rust Tracing",
    details: "Terminal de registro en tiempo real que transmite los eventos internos de LibP2P, handshakes Bluetooth LE y operaciones de base de datos transaccional Sled directamente a la pantalla.",
    latency: "< 10ms",
    encryption: "Local Loopback"
  }
];
