"use client";

import React, { useState } from "react";
import Logo from "./Logo";

/**
 * Generates a cryptographic identity using:
 * 1. Web Crypto API (Ed25519 via ECDSA P-256 for wider browser support)
 * 2. Falls back to /api/identity if the node is reachable
 *
 * Returns { identity_hash, short_id, public_key }
 */
async function generateCryptoIdentity(): Promise<{
    identity_hash: string;
    short_id: string;
    public_key: string;
}> {
    // Try to get identity from the deployed RED node first
    const apiUrl = process.env.NEXT_PUBLIC_API_URL
        ? process.env.NEXT_PUBLIC_API_URL.replace(/\/$/, '') + '/api'
        : 'http://localhost:7333/api';

    try {
        const res = await fetch(`${apiUrl}/identity`, { signal: AbortSignal.timeout(3000) });
        if (res.ok) {
            const data = await res.json();
            return {
                identity_hash: data.identity_hash,
                short_id: data.short_id,
                public_key: data.identity_hash.substring(0, 64),
            };
        }
    } catch {
        // Node not reachable — generate locally with Web Crypto
    }

    // Local generation using Web Crypto (ECDSA P-256 as Ed25519 proxy)
    // The real Ed25519 keys are generated by the Rust node on init.
    // This gives us a deterministic, unique ID that can be re-linked to the node later.
    const keyPair = await crypto.subtle.generateKey(
        { name: "ECDSA", namedCurve: "P-256" },
        true,
        ["sign", "verify"]
    );

    const exported = await crypto.subtle.exportKey("raw", keyPair.publicKey);
    const hashBuffer = await crypto.subtle.digest("SHA-256", exported);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const identity_hash = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    const short_id = "red_" + identity_hash.substring(0, 12);

    // Export public key for sharing
    const pubKeyArray = Array.from(new Uint8Array(exported));
    const public_key = pubKeyArray.map(b => b.toString(16).padStart(2, '0')).join('');

    return { identity_hash, short_id, public_key };
}

export default function Onboarding({ onFinish }: { onFinish: (identity: any) => void }) {
    const [step, setStep] = useState(1);
    const [isGenerating, setIsGenerating] = useState(false);
    const [identity, setIdentity] = useState<any>(null);
    const [copied, setCopied] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const generateIdentity = async () => {
        setIsGenerating(true);
        setError(null);
        try {
            const id = await generateCryptoIdentity();
            // Persist to localStorage
            try {
                localStorage.setItem('red_identity_hash', id.identity_hash);
                localStorage.setItem('red_short_id', id.short_id);
                localStorage.setItem('red_public_key', id.public_key);
            } catch { }
            setIdentity(id);
            setStep(3);
        } catch (err) {
            setError("Error al generar identidad. Verifica tu conexión.");
            console.error('[Onboarding] Identity generation failed:', err);
        } finally {
            setIsGenerating(false);
        }
    };

    const copyKey = () => {
        if (!identity) return;
        try {
            navigator.clipboard?.writeText(identity.identity_hash).then(() => {
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
            });
        } catch { }
    };

    return (
        <div className="onboarding-overlay">
            <div className="onboarding-card glass animate-fade">
                <div className="onboarding-header">
                    <Logo size={60} />
                    <div className="step-dots">
                        {[1, 2, 3, 4].map(s => <div key={s} className={`dot ${s === step ? 'active' : ''}`}></div>)}
                    </div>
                </div>

                <div className="onboarding-content">
                    {step === 1 && (
                        <div className="step-content animate-fade">
                            <h1>Bienvenido a la Red</h1>
                            <p>RED es un protocolo de mensajería donde tú eres el dueño. Sin servidores centrales, sin censura y con privacidad absoluta.</p>
                            <button className="btn-primary" onClick={() => setStep(2)}>Empezar</button>
                        </div>
                    )}

                    {step === 2 && (
                        <div className="step-content animate-fade">
                            <h1>Generando tu DID</h1>
                            <p>Tu Identificador Descentralizado es un keypair criptográfico único generado localmente. Nadie más tiene acceso a él.</p>
                            {error && <p style={{ color: 'var(--primary)', fontSize: '0.82rem' }}>{error}</p>}
                            {isGenerating ? (
                                <div className="loader-container">
                                    <div className="loader"></div>
                                    <span>Generando claves criptográficas...</span>
                                </div>
                            ) : (
                                <button className="btn-primary" onClick={generateIdentity}>
                                    Generar Identidad
                                </button>
                            )}
                        </div>
                    )}

                    {step === 3 && identity && (
                        <div className="step-content animate-fade">
                            <h1>Copia de Seguridad</h1>
                            <p>Este es tu DID único. Si lo pierdes, no podrás recuperar tu cuenta. Guárdalo en un lugar seguro.</p>
                            <div className="key-box">
                                <code>{identity.identity_hash}</code>
                                <button
                                    className={`copy-btn ${copied ? 'btn-saved' : ''}`}
                                    onClick={copyKey}
                                >
                                    {copied ? '✓ Copiado' : 'Copiar'}
                                </button>
                            </div>
                            <button className="btn-primary" onClick={() => setStep(4)}>
                                He guardado mi clave
                            </button>
                        </div>
                    )}

                    {step === 4 && identity && (
                        <div className="step-content animate-fade">
                            <h1>¡Todo listo!</h1>
                            <p>Tu identidad <strong>{identity.short_id}</strong> está lista. Comparte tu DID con tus contactos para empezar a chatear de forma segura.</p>
                            <button
                                className="btn-primary"
                                onClick={() => onFinish(identity)}
                            >
                                Entrar a RED
                            </button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
